/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static int  result;

    printf("calculating %i + %i\n", arg1.num1, arg1.num2);
    result = arg1.num1 + arg1.num2;

	return &result;
}

int *
resta_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static int  result;

    printf("calculating %i - %i\n", arg1.num1, arg1.num2);
    result = arg1.num1 - arg1.num2;

	return &result;
}

int *
multiplicacion_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static int  result;

    printf("calculating %i x %i\n", arg1.num1, arg1.num2);
    result = arg1.num1 * arg1.num2;

	return &result;
}

float *
division_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static float  result;

	// La comprobación se hace antes de realizar la llamada, en el cliente
	printf("calculating %i / %i\n", arg1.num1, arg1.num2);
	result = (float) arg1.num1 / (float) arg1.num2;

    return &result;
}
