/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int num1;
	int num2;
};
typedef struct inputs inputs;

#define CALCULADORAPROG 0x200000ff
#define CALCULADORAVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(inputs , CLIENT *);
extern  int * suma_1_svc(inputs , struct svc_req *);
#define RESTA 2
extern  int * resta_1(inputs , CLIENT *);
extern  int * resta_1_svc(inputs , struct svc_req *);
#define MULTIPLICACION 3
extern  int * multiplicacion_1(inputs , CLIENT *);
extern  int * multiplicacion_1_svc(inputs , struct svc_req *);
#define DIVISION 4
extern  float * division_1(inputs , CLIENT *);
extern  float * division_1_svc(inputs , struct svc_req *);
extern int calculadoraprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICACION 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calculadoraprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
