/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>	// atoi, convertir una cadena a int
#include "calculadora.h"


void
calculadoraprog_1(char *host, int num1, char op, int num2)
{
	// Cliente
	CLIENT *clnt;
	
	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORAPROG, CALCULADORAVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	
	// Argumentos de entrada
	inputs arg;
	arg.num1 = num1;
	arg.num2 = num2;

	// Resultado(s)
	int  *result_1 = (int*)NULL;		// resultado para la suma, resta y multiplicacion
	float *result_2 = (float*)NULL;	// resultado para la división
	
	switch(op) {
		case('+'):	result_1 = suma_1(arg, clnt);	break;
		case('-'):	result_1 = resta_1(arg, clnt);	break;
		case('x'):	result_1 = multiplicacion_1(arg, clnt);	break;
		case('/'): 	result_2 = division_1(arg, clnt); break;
		default:	
			clnt_perror (clnt, "invalid operator, [valid operators: +|-|x|/ ]\n"); 	
			exit(-1);
	}
	
	if((result_1==(int *)NULL) && (result_2==(float*)NULL)) { 
		clnt_perror (clnt, "call failed");
		exit(-1);
	} else if(result_1==(int *)NULL) 
		printf("%i %c %i = %.2f\n", num1, op, num2, *result_2); // Resultado de division (float->result_2)
	else 	
		printf("%i %c %i = %i\n", num1, op, num2, *result_1);	// Resultado de suma, multp, y resta (int->result_1)

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	if (argc != 5) {
		printf ("usage: %s server_host float1 +|-|x|/ float2\n", argv[0]);
		exit (1);
	}

	/* Procesamiento de argumentos */
	char *host = argv[1];
	int f1 = atoi(argv[2]);
	char op = *argv[3];
	int f2 = atoi(argv[4]);
	
	if(op == '/' && f2==0) {
		printf ("stop: math error, cannot divide by 0\n");
		exit (1);
	}
	
	printf("calling server: %s with the following operation %i %c %i\n", host, f1, op, f2);
	
	calculadoraprog_1 (host, f1, op, f2);

    exit (0);
}
